# Generated by Django 3.0.11 on 2020-12-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='manager',
            new_name='user',
        ),
    ]
