# Generated by Django 3.0.11 on 2020-12-20 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0002_auto_20201220_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='user1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deputy_director', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='info',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
