# Generated by Django 3.0.11 on 2020-12-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20201220_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='user1',
            new_name='deputy_director',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='user',
            new_name='manager',
        ),
    ]
