# Generated by Django 3.0.11 on 2021-01-01 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_auto_20201228_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='wrong Phone number', regex='^[0][5][0|2|3|4|5|6|9]{1}[-]{0,1}[0-9]{7}$')]),
        ),
    ]
