# Generated by Django 3.0.11 on 2020-12-21 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_auto_20201219_2012'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('start_hour', models.TimeField()),
                ('ending_hour', models.TimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
                ('worker', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
