# Generated by Django 3.0.11 on 2020-12-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
