# Generated by Django 3.0.11 on 2020-12-24 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='project.File'),
        ),
    ]
