# Generated by Django 3.0.11 on 2020-12-24 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20201224_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='project_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='project.Project'),
        ),
    ]
