# Generated by Django 3.0.11 on 2020-12-24 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20201224_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='file1',
        ),
        migrations.RemoveField(
            model_name='file',
            name='project_code',
        ),
        migrations.AddField(
            model_name='project',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='project.File'),
        ),
    ]
