# Generated by Django 3.0.11 on 2021-01-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20201226_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='address',
        ),
        migrations.RemoveField(
            model_name='project',
            name='architect',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.AddField(
            model_name='project',
            name='address_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='architect_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='project',
            name='architect_first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='architect_phone_no',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='project',
            name='architect_second_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='contractor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='project',
            name='contractor_first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='contractor_phone_no',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='project',
            name='contractor_second_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='project',
            name='owner_first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='owner_phone_no',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='project',
            name='owner_second_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='property_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='street',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Architect',
        ),
        migrations.DeleteModel(
            name='Contractor',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
